In [1]:
# prep: import modules and get pwd
import pymysql
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import getpass  # To get the password without showing the input
password = getpass.getpass()

pd.set_option('display.max_columns', None) # Used to show all columns

········

## Loading data

#### Data is loadaded after querying in MySQL.

In [187]:
connection_string = 'mysql+pymysql://root:' + password + '@localhost/sakila'
engine = create_engine(connection_string)
query = '''SELECT * FROM sakila.film f
JOIN sakila.inventory i USING (film_id)
JOIN sakila.rental fa USING (inventory_id)
JOIN sakila.film_category fc USING (film_id)
JOIN sakila.category c USING (category_id)
JOIN sakila.payment p USING (rental_id);'''

sakila = pd.read_sql_query(query, engine)
sakila.head()

,rental_id,category_id,film_id,inventory_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update,store_id,last_update,rental_date,customer_id,return_date,staff_id,last_update,last_update,name,last_update,payment_id,customer_id,staff_id,amount,payment_date,last_update
0,10895,1,19,93,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-02 01:16:59,77,2005-08-03 02:41:59,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,2104,77,1,0.99,2005-08-02 01:16:59,2006-02-15 22:12:50
1,12268,1,19,93,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-18 04:26:54,39,2005-08-23 06:40:54,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,1093,39,2,0.99,2005-08-18 04:26:54,2006-02-15 22:12:38
2,3150,1,19,94,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-06-20 20:35:28,34,2005-06-26 01:01:28,1,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,930,34,1,0.99,2005-06-20 20:35:28,2006-02-15 22:12:36
3,5072,1,19,94,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-07-09 05:01:58,254,2005-07-18 08:17:58,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,6848,254,1,3.99,2005-07-09 05:01:58,2006-02-15 22:14:52
4,9080,1,19,94,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-07-30 08:02:39,276,2005-08-06 12:02:39,1,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,7479,276,1,1.99,2005-07-30 08:02:39,2006-02-15 22:15:16

#### Checking data

In [188]:
sakila.shape
sakila.dtypes
sakila.isna().sum()
sakila.drop_duplicates()
sakila.head(2)

,rental_id,category_id,film_id,inventory_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update,store_id,last_update,rental_date,customer_id,return_date,staff_id,last_update,last_update,name,last_update,payment_id,customer_id,staff_id,amount,payment_date,last_update
0,10895,1,19,93,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-02 01:16:59,77,2005-08-03 02:41:59,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,2104,77,1,0.99,2005-08-02 01:16:59,2006-02-15 22:12:50
1,12268,1,19,93,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-18 04:26:54,39,2005-08-23 06:40:54,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,1093,39,2,0.99,2005-08-18 04:26:54,2006-02-15 22:12:38

#### Isolating the rental_date month in a separate column that we call 'may_target'

In [189]:
sakila['may_target'] = pd.DatetimeIndex(sakila['rental_date']).month
sakila.head(2)

,rental_id,category_id,film_id,inventory_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update,store_id,last_update,rental_date,customer_id,return_date,staff_id,last_update,last_update,name,last_update,payment_id,customer_id,staff_id,amount,payment_date,last_update,may_target
0,10895,1,19,93,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-02 01:16:59,77,2005-08-03 02:41:59,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,2104,77,1,0.99,2005-08-02 01:16:59,2006-02-15 22:12:50,8
1,12268,1,19,93,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-18 04:26:54,39,2005-08-23 06:40:54,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,1093,39,2,0.99,2005-08-18 04:26:54,2006-02-15 22:12:38,8

#### Create a new column for duration of customer rental which is return date - rental date (a timedelta64 dtype)

In [190]:
sakila['duration_of_rental'] = (sakila['return_date'] - sakila['rental_date'])

sakila.head() # This returns 184 NaTs in the new column

sum(sakila['duration_of_rental'].isna())

# Replace the NaTs with the column median 

time_median = sakila['duration_of_rental'].median()
time_median
sakila['duration_of_rental'] = sakila['duration_of_rental'].replace({np.nan: time_median}).dt.days

#### Function: create a new column to convert our target into a boolean. If month is may return 1, else return 0.

In [191]:
def boolean(x):
        
        if x == 5:
            return 1
        else:
            return 0

sakila['may_target'] = list(map(boolean, sakila['may_target']))
sakila.head(10)

,rental_id,category_id,film_id,inventory_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update,store_id,last_update,rental_date,customer_id,return_date,staff_id,last_update,last_update,name,last_update,payment_id,customer_id,staff_id,amount,payment_date,last_update,may_target,duration_of_rental
0,10895,1,19,93,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-02 01:16:59,77,2005-08-03 02:41:59,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,2104,77,1,0.99,2005-08-02 01:16:59,2006-02-15 22:12:50,0,1
1,12268,1,19,93,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-18 04:26:54,39,2005-08-23 06:40:54,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,1093,39,2,0.99,2005-08-18 04:26:54,2006-02-15 22:12:38,0,5
2,3150,1,19,94,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-06-20 20:35:28,34,2005-06-26 01:01:28,1,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,930,34,1,0.99,2005-06-20 20:35:28,2006-02-15 22:12:36,0,5
3,5072,1,19,94,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-07-09 05:01:58,254,2005-07-18 08:17:58,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,6848,254,1,3.99,2005-07-09 05:01:58,2006-02-15 22:14:52,0,9
4,9080,1,19,94,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-07-30 08:02:39,276,2005-08-06 12:02:39,1,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,7479,276,1,1.99,2005-07-30 08:02:39,2006-02-15 22:15:16,0,7
5,14603,1,19,94,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-08-21 17:51:06,26,2005-08-28 15:36:06,1,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,715,26,2,1.99,2005-08-21 17:51:06,2006-02-15 22:12:34,0,6
6,588,1,19,95,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-05-28 12:08:37,89,2005-05-29 16:25:37,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,2410,89,2,0.99,2005-05-28 12:08:37,2006-02-15 22:12:55,1,1
7,2867,1,19,95,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-06-20 00:08:38,483,2005-06-23 19:35:38,1,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,13039,483,2,0.99,2005-06-20 00:08:38,2006-02-15 22:19:55,0,3
8,6030,1,19,95,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-07-11 02:37:51,36,2005-07-16 22:34:51,2,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,991,36,2,0.99,2005-07-11 02:37:51,2006-02-15 22:12:37,0,5
9,7788,1,19,95,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,1,2006-02-15 05:09:17,2005-07-28 07:21:55,487,2005-08-03 06:33:55,1,2006-02-15 21:30:53,2006-02-15 05:07:09,Action,2006-02-15 04:46:27,13146,487,1,0.99,2005-07-28 07:21:55,2006-02-15 22:20:01,0,5

#### Dropping columns that we will not be using and reordering the remaining ones.

In [192]:
sakila = sakila.drop(['category_id', 'rental_id', 'inventory_id', 'description', 'release_year', 'language_id', 'original_language_id', 'last_update',
                     'last_update', 'rental_date', 'customer_id', 'return_date', 'staff_id', 'replacement_cost', 'payment_id', 'payment_date'], axis=1)

In [193]:
sakila = sakila[['film_id', 'title', 'rental_duration', 'rental_rate', 'length',
       'rating', 'special_features', 'store_id', 'name', 'amount', 'duration_of_rental', 'may_target']]

In [194]:
sakila.head(60)

,film_id,title,rental_duration,rental_rate,length,rating,special_features,store_id,name,amount,duration_of_rental,may_target
0,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,0.99,1,0
1,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,0.99,5,0
2,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,0.99,5,0
3,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,3.99,9,0
4,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,1.99,7,0
5,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,1.99,6,0
6,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,0.99,1,1
7,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,0.99,3,0
8,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,0.99,5,0
9,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,0.99,5,0
10,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,0.99,1,0
11,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,3.99,8,0
12,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",1,Action,3.99,9,0
13,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2,Action,0.99,3,0
14,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2,Action,0.99,2,0
15,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2,Action,1.99,7,0
16,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2,Action,0.99,5,0
17,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2,Action,0.99,1,0
18,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2,Action,0.99,2,0
19,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2,Action,1.99,7,0
20,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2,Action,0.99,2,0
21,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,4.99,1,1
22,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,4.99,1,0
23,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,8.99,6,0
24,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,4.99,2,0
25,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,4.99,3,0
26,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,10.99,8,1
27,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,9.99,8,0
28,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,10.99,8,0
29,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,8.99,7,0
30,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",1,Action,4.99,1,0
31,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,9.99,7,0
32,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,4.99,3,0
33,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,10.99,8,0
34,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,6.99,5,0
35,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,9.99,7,0
36,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,10.99,9,0
37,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,5.99,4,0
38,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,4.99,1,0
39,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,8.99,6,0
40,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,4.99,5,0
41,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,8.99,7,0
42,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",2,Action,4.99,0,0
43,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,2.99,2,1
44,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,6.99,9,0
45,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,4.99,7,0
46,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,2.99,5,0
47,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,2.99,4,0
48,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,2.99,1,1
49,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,3.99,6,0
50,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,2.99,3,0
51,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,3.99,5,0
52,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",1,Action,2.99,2,0
53,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",1,Action,4.99,7,0
54,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",1,Action,2.99,4,0
55,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",1,Action,2.99,0,0
56,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",1,Action,2.99,6,0
57,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",1,Action,6.99,9,1
58,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",1,Action,3.99,6,0
59,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",1,Action,2.99,6,0

In [195]:
sakila['special_features'].unique()

array(['Commentaries,Deleted Scenes,Behind the Scenes',
       'Commentaries,Behind the Scenes',
       'Trailers,Commentaries,Deleted Scenes', 'Trailers,Commentaries',
       'Deleted Scenes', 'Trailers,Commentaries,Behind the Scenes',
       'Commentaries,Deleted Scenes', 'Behind the Scenes', 'Trailers',
       'Deleted Scenes,Behind the Scenes',
       'Trailers,Deleted Scenes,Behind the Scenes',
       'Trailers,Commentaries,Deleted Scenes,Behind the Scenes',
       'Trailers,Behind the Scenes', 'Commentaries',
       'Trailers,Deleted Scenes'], dtype=object)

In [196]:
def cat_store(x):
        
        if x == 1:
            return 'A'
        else:
            return 'B'

#sakila['store_id'] = list(map(cat_store, sakila['store_id']))
sakila['store_id'] = sakila['store_id'].apply(cat_store)
sakila['store_id'].unique()
sakila.head(60)

,film_id,title,rental_duration,rental_rate,length,rating,special_features,store_id,name,amount,duration_of_rental,may_target
0,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,0.99,1,0
1,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,0.99,5,0
2,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,0.99,5,0
3,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,3.99,9,0
4,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,1.99,7,0
5,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,1.99,6,0
6,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,0.99,1,1
7,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,0.99,3,0
8,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,0.99,5,0
9,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,0.99,5,0
10,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,0.99,1,0
11,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,3.99,8,0
12,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",A,Action,3.99,9,0
13,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",B,Action,0.99,3,0
14,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",B,Action,0.99,2,0
15,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",B,Action,1.99,7,0
16,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",B,Action,0.99,5,0
17,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",B,Action,0.99,1,0
18,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",B,Action,0.99,2,0
19,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",B,Action,1.99,7,0
20,19,AMADEUS HOLY,6,0.99,113,PG,"Commentaries,Deleted Scenes,Behind the Scenes",B,Action,0.99,2,0
21,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,4.99,1,1
22,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,4.99,1,0
23,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,8.99,6,0
24,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,4.99,2,0
25,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,4.99,3,0
26,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,10.99,8,1
27,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,9.99,8,0
28,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,10.99,8,0
29,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,8.99,7,0
30,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",A,Action,4.99,1,0
31,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,9.99,7,0
32,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,4.99,3,0
33,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,10.99,8,0
34,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,6.99,5,0
35,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,9.99,7,0
36,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,10.99,9,0
37,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,5.99,4,0
38,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,4.99,1,0
39,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,8.99,6,0
40,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,4.99,5,0
41,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,8.99,7,0
42,21,AMERICAN CIRCUS,3,4.99,129,R,"Commentaries,Behind the Scenes",B,Action,4.99,0,0
43,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,2.99,2,1
44,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,6.99,9,0
45,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,4.99,7,0
46,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,2.99,5,0
47,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,2.99,4,0
48,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,2.99,1,1
49,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,3.99,6,0
50,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,2.99,3,0
51,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,3.99,5,0
52,29,ANTITRUST TOMATOES,5,2.99,168,NC-17,"Trailers,Commentaries,Deleted Scenes",A,Action,2.99,2,0
53,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",A,Action,4.99,7,0
54,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",A,Action,2.99,4,0
55,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",A,Action,2.99,0,0
56,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",A,Action,2.99,6,0
57,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",A,Action,6.99,9,1
58,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",A,Action,3.99,6,0
59,56,BAREFOOT MANCHURIAN,6,2.99,129,G,"Trailers,Commentaries",A,Action,2.99,6,0

#### Xy split and train and test split

In [197]:
y = sakila['may_target']
X = sakila.drop('may_target', axis=1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1337)

In [198]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler

X_train_num = X_train.select_dtypes(include = np.number)
X_train_num = X_train_num.drop('film_id', axis = 1)

# Scaling data
transformer = MinMaxScaler().fit(X_train_num) # need to keep transformer
X_train_normalized = transformer.transform(X_train_num)
X_train_norm = pd.DataFrame(X_train_normalized, columns=X_train_num.columns)
X_train_norm

       rental_duration  rental_rate    length    amount  duration_of_rental
0                 1.00          0.0  0.064748  0.082569            0.333333
1                 0.50          1.0  0.244604  0.416180            0.555556
2                 1.00          0.0  0.460432  0.165972            0.888889
3                 0.00          0.0  0.172662  0.249374            0.444444
4                 1.00          0.5  0.237410  0.249374            0.555556
...                ...          ...       ...       ...                 ...
12830             0.00          0.5  0.539568  0.416180            0.444444
12831             1.00          1.0  0.856115  0.499583            0.777778
12832             0.25          0.5  0.697842  0.249374            0.000000
12833             0.75          0.5  0.964029  0.249374            0.222222
12834             0.00          0.5  0.539568  0.666389            0.777778

[12835 rows x 5 columns]

In [209]:
X_train_cat = X.select_dtypes(object)
X_train_cat = X_train_cat.drop(['title', 'special_features'], axis = 1)
display(X_train_cat.head())
display(X_train_cat.tail())

X_train_cat.shape

  rating store_id    name
0     PG        A  Action
1     PG        A  Action
2     PG        A  Action
3     PG        A  Action
4     PG        A  Action

      rating store_id    name
16039      R        B  Travel
16040      R        B  Travel
16041      R        B  Travel
16042      R        B  Travel
16043      R        B  Travel

(16044, 3)

In [205]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(X_train_cat)
encoded_for_p = encoder.transform(X_train_cat).toarray()
encoded_for_p
display(encoder.categories_)
cols = [colname for row in encoder.categories_ for colname in row]
display(cols)
cat_num = pd.DataFrame(encoded_for_p, columns=cols)
cols_to_drop = [row[0] for row in encoder.categories_]
cols_to_drop
cat_num = cat_num.drop(cols_to_drop,axis=1)
cat_num.head()

[array(['G', 'NC-17', 'PG', 'PG-13', 'R'], dtype=object),
 array(['A', 'B'], dtype=object),
 array(['Action', 'Animation', 'Children', 'Classics', 'Comedy',
        'Documentary', 'Drama', 'Family', 'Foreign', 'Games', 'Horror',
        'Music', 'New', 'Sci-Fi', 'Sports', 'Travel'], dtype=object)]

['G',
 'NC-17',
 'PG',
 'PG-13',
 'R',
 'A',
 'B',
 'Action',
 'Animation',
 'Children',
 'Classics',
 'Comedy',
 'Documentary',
 'Drama',
 'Family',
 'Foreign',
 'Games',
 'Horror',
 'Music',
 'New',
 'Sci-Fi',
 'Sports',
 'Travel']

,NC-17,PG,PG-13,R,B,Animation,Children,Classics,Comedy,Documentary,Drama,Family,Foreign,Games,Horror,Music,New,Sci-Fi,Sports,Travel
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [206]:
# build X_train and y_train
# remember: y = data['status'], y_train selected in train_test_split
X_train_transformed = np.concatenate([X_train_norm, X_train_cat], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 12835 and the array at index 1 has size 16044