In [193]:
# prep: import modules and get pwd
import pymysql
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
from scipy import stats
import getpass  # To get the password without showing the input
password = getpass.getpass()

pd.set_option('display.max_columns', None) # Used to show all columns
#pd.set_option('display.max_rows', None) # Used to show all columns

········

## Loading data

#### Data is loadaded after querying in MySQL.

In [209]:
connection_string = 'mysql+pymysql://root:' + password + '@localhost/sakila'
engine = create_engine(connection_string)
query = '''SELECT * FROM sakila.film
LEFT JOIN sakila.inventory USING (film_id)
LEFT JOIN sakila.rental r USING (inventory_id)
LEFT JOIN sakila.film_category fc USING (film_id)
LEFT JOIN sakila.category c USING (category_id)
LEFT JOIN sakila.payment p USING (rental_id);'''

sakila = pd.read_sql_query(query, engine)
sakila.head()
sakila.shape

(16090, 32)

## Checking and understanding data

In [195]:
#sakila.shape
#sakila.dtypes
#sakila.isna().sum()
#sakila.drop_duplicates()
#sakila.head(2)

#sakila1 = sakila.groupby(['title']).agg({'may_target': sum})
#sakila['title'].value_counts()
#sakila1.value_counts()

## Cleaning and preparing data for analysis

#### Dropping columns that we certainly know will not be used beyond this point.

In [210]:
sakila = sakila.drop(['category_id', 'rental_duration', 'title', 'inventory_id', 'description', 'release_year', 'language_id', 'original_language_id', 'last_update',
                     'last_update', 'customer_id', 'staff_id', 'store_id', 'replacement_cost', 'payment_id', 'amount', 'payment_date'], axis=1)

#### Renaming column 'name' to 'genre'

In [211]:
sakila = sakila.rename(columns = {'name' : 'genre'})

#### Isolating the rental_date month in a separate column that we call 'may_target'

In [212]:
sakila['may_target'] = pd.DatetimeIndex(sakila['rental_date']).month
sakila.head(2)

,rental_id,film_id,rental_rate,length,rating,special_features,rental_date,return_date,genre,may_target
0,4863.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2005-07-08 19:03:15,2005-07-11 21:29:15,Documentary,7.0
1,11433.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2005-08-02 20:13:10,2005-08-11 21:35:10,Documentary,8.0

#### Function: create a new column to convert target into a boolean. If month is May return 1, else return 0.

In [213]:
def maytarget(x):
        
        if x == 5:
            return 1
        else:
            return 0

sakila['may_target'] = list(map(maytarget, sakila['may_target']))
sakila.head(2)

,rental_id,film_id,rental_rate,length,rating,special_features,rental_date,return_date,genre,may_target
0,4863.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2005-07-08 19:03:15,2005-07-11 21:29:15,Documentary,0
1,11433.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2005-08-02 20:13:10,2005-08-11 21:35:10,Documentary,0

#### Create a new column for duration of customer rental which is return date - rental date (a timedelta64 dtype)

In [214]:
sakila['duration_of_rental'] = (sakila['return_date'] - sakila['rental_date'])

sakila.head() # This returns 184 NaTs in the new column

sum(sakila['duration_of_rental'].isna())

# Replace the NaTs with the column median 

time_median = sakila['duration_of_rental'].median()
time_median
sakila['duration_of_rental'] = sakila['duration_of_rental'].replace({np.nan: time_median}).dt.days

sakila.head()

,rental_id,film_id,rental_rate,length,rating,special_features,rental_date,return_date,genre,may_target,duration_of_rental
0,4863.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2005-07-08 19:03:15,2005-07-11 21:29:15,Documentary,0,3
1,11433.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2005-08-02 20:13:10,2005-08-11 21:35:10,Documentary,0,9
2,14714.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2005-08-21 21:27:43,2005-08-30 22:26:43,Documentary,0,9
3,16052.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2022-09-17 10:02:37,NaT,Documentary,0,5
4,972.0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",2005-05-30 20:21:07,2005-06-06 00:36:07,Documentary,1,6

In [215]:
#sakila1 = sakila.groupby(['title']).agg({'may_target': sum})
#sakila['title'].value_counts()
#sakila1.value_counts()

#### Reordering columns.

In [216]:
sakila = sakila[['film_id', 'rental_rate', 'length',
       'rating', 'special_features', 'genre', 'duration_of_rental', 'may_target']]

In [217]:
sakila.head(10)

,film_id,rental_rate,length,rating,special_features,genre,duration_of_rental,may_target
0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,3,0
1,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,9,0
2,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,9,0
3,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,5,0
4,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,6,1
5,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,5,0
6,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,3,0
7,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,6,0
8,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,7,0
9,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,3,0

In [204]:
#### Grouping by film.

In [218]:
sakila = sakila.groupby(['film_id', 'rental_rate', 'length', 'rating', 'special_features', 'genre']).agg({'duration_of_rental': np.mean, 'may_target':sum, }).reset_index()
sakila

,film_id,rental_rate,length,rating,special_features,genre,duration_of_rental,may_target
0,1,0.99,86,PG,"Deleted Scenes,Behind the Scenes",Documentary,4.600000,2
1,2,4.99,48,G,"Trailers,Deleted Scenes",Horror,5.222222,0
2,3,2.99,50,NC-17,"Trailers,Deleted Scenes",Documentary,2.833333,1
3,4,2.99,117,G,"Commentaries,Behind the Scenes",Horror,4.391304,2
4,5,2.99,130,G,Deleted Scenes,Family,6.583333,1
...,...,...,...,...,...,...,...,...
995,996,0.99,183,G,"Trailers,Behind the Scenes",Documentary,4.000000,0
996,997,0.99,179,NC-17,"Trailers,Behind the Scenes",Music,4.666667,0
997,998,0.99,105,NC-17,Deleted Scenes,Horror,5.222222,1
998,999,2.99,101,R,"Trailers,Deleted Scenes",Children,5.176471,1
999,1000,4.99,50,NC-17,"Trailers,Commentaries,Behind the Scenes",Comedy,4.096774,3

In [188]:
#### 'may_target' renamed to 'times_rented' (in May)

In [219]:
sakila = sakila.rename(columns = {'may_target': 'times_rented'})

In [190]:
#### Function to recuperate the 'may_target' column

In [222]:
def maytarget(x):
        
        if x > 0:
            return 1
        else:
            return 0

sakila['may_target'] = list(map(maytarget, sakila['times_rented']))
sakila.head(10)

(1000, 9)

#### Xy split and train and test split

In [223]:
sakila.columns

Index(['film_id', 'rental_rate', 'length', 'rating', 'special_features',
       'genre', 'duration_of_rental', 'times_rented', 'may_target'],
      dtype='object')

In [224]:
y = sakila['may_target']
X = sakila.drop(['may_target', 'film_id'], axis=1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1337)

#### Scaling

In [233]:
from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler

X_train_num = X_train.select_dtypes(include = np.number)


# Scaling data
transformer = MinMaxScaler().fit(X_train_num) # need to keep transformer
X_train_num_norm = transformer.transform(X_train_num)
X_train_num_norm = pd.DataFrame(X_train_num_norm, columns=X_train_num.columns)
X_train_num_norm

     rental_rate    length  duration_of_rental  times_rented
0            1.0  0.769784            0.527239           0.2
1            0.0  0.151079            0.550746           0.2
2            0.5  0.258993            0.644776           0.2
3            1.0  0.223022            0.534534           0.8
4            0.0  0.733813            0.550746           0.4
..           ...       ...                 ...           ...
795          0.0  0.151079            0.237313           0.0
796          0.0  0.683453            0.347840           0.2
797          1.0  0.467626            0.564179           0.4
798          1.0  0.906475            0.416418           0.2
799          0.5  0.316547            0.582090           0.2

[800 rows x 4 columns]

In [234]:
from sklearn.preprocessing import OneHotEncoder
X_train_cat = X_train.select_dtypes(object)

encoder = OneHotEncoder(drop='first').fit(X_train_cat)
encoded = encoder.transform(X_train_cat).toarray()

cols = encoder.get_feature_names_out(input_features=X_train_cat.columns)

X_train_cat_norm = onehot_encoded = pd.DataFrame(encoded, columns=cols)
X_train_cat_norm.head()

,rating_NC-17,rating_PG,rating_PG-13,rating_R,special_features_Commentaries,"special_features_Commentaries,Behind the Scenes","special_features_Commentaries,Deleted Scenes","special_features_Commentaries,Deleted Scenes,Behind the Scenes",special_features_Deleted Scenes,"special_features_Deleted Scenes,Behind the Scenes",special_features_Trailers,"special_features_Trailers,Behind the Scenes","special_features_Trailers,Commentaries","special_features_Trailers,Commentaries,Behind the Scenes","special_features_Trailers,Commentaries,Deleted Scenes","special_features_Trailers,Commentaries,Deleted Scenes,Behind the Scenes","special_features_Trailers,Deleted Scenes","special_features_Trailers,Deleted Scenes,Behind the Scenes",genre_Animation,genre_Children,genre_Classics,genre_Comedy,genre_Documentary,genre_Drama,genre_Family,genre_Foreign,genre_Games,genre_Horror,genre_Music,genre_New,genre_Sci-Fi,genre_Sports,genre_Travel
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [235]:
X_train_cat_norm.shape

(800, 33)

In [236]:
# build X_train and y_train
# remember: y = data['status'], y_train selected in train_test_split
X_train_transformed = np.concatenate([X_train_num_norm, X_train_cat_norm], axis=1)

In [237]:
X_train_transformed

array([[1.        , 0.76978417, 0.52723881, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.15107914, 0.55074627, ..., 0.        , 0.        ,
        0.        ],
       [0.5       , 0.25899281, 0.64477612, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.4676259 , 0.5641791 , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.90647482, 0.41641791, ..., 0.        , 0.        ,
        0.        ],
       [0.5       , 0.31654676, 0.58208955, ..., 0.        , 0.        ,
        0.        ]])

In [238]:
from sklearn.linear_model import LogisticRegression
classification = LogisticRegression(random_state=0, solver='lbfgs', max_iter = 5000).fit(X_train_transformed, y_train)

# multi_class specifies the targets are more than 2
# solver = lbfgs has a limited number of iterations, alternative is 'saga'
# add: max_iter = XXXX to increase the number of iterations with 'lbfgs'

In [239]:
# for numericals
X_test_num = X_test.select_dtypes(include = np.number)

# Scaling data
# we use the transformer that was trained on the training data
X_test_normalized = transformer.transform(X_test_num)
X_test_norm = pd.DataFrame(X_test_normalized)

In [240]:
# for categoricals
X_test_categorical = X_test.select_dtypes(include = object)

# Encode again
encoder = OneHotEncoder(drop='first').fit(X_test_categorical)
encoded = encoder.transform(X_test_categorical).toarray()

cols = encoder.get_feature_names(input_features=X_test_categorical.columns)

X_test_cat = onehot_encoded = pd.DataFrame(encoded, columns=cols)
X_test_cat.head()

C:\Users\lalo_\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,rating_NC-17,rating_PG,rating_PG-13,rating_R,special_features_Commentaries,"special_features_Commentaries,Behind the Scenes","special_features_Commentaries,Deleted Scenes","special_features_Commentaries,Deleted Scenes,Behind the Scenes",special_features_Deleted Scenes,"special_features_Deleted Scenes,Behind the Scenes",special_features_Trailers,"special_features_Trailers,Behind the Scenes","special_features_Trailers,Commentaries","special_features_Trailers,Commentaries,Behind the Scenes","special_features_Trailers,Commentaries,Deleted Scenes","special_features_Trailers,Commentaries,Deleted Scenes,Behind the Scenes","special_features_Trailers,Deleted Scenes","special_features_Trailers,Deleted Scenes,Behind the Scenes",genre_Animation,genre_Children,genre_Classics,genre_Comedy,genre_Documentary,genre_Drama,genre_Family,genre_Foreign,genre_Games,genre_Horror,genre_Music,genre_New,genre_Sci-Fi,genre_Sports,genre_Travel
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [241]:
X_test_transformed = np.concatenate([X_test_norm, X_test_cat], axis=1)

X_test_transformed

array([[0.        , 0.37410072, 0.56119403, ..., 0.        , 0.        ,
        0.        ],
       [0.5       , 0.96402878, 0.65820896, ..., 0.        , 0.        ,
        0.        ],
       [0.5       , 0.31654676, 0.48358209, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.5       , 0.27338129, 0.53628014, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.29496403, 0.54626866, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.4028777 , 0.5421981 , ..., 0.        , 0.        ,
        0.        ]])

In [242]:
predictions = classification.predict(X_test_transformed)
classification.score(X_test_transformed, y_test)

1.0

In [243]:
X_test_transformed = np.concatenate([X_test_norm, X_test_cat], axis=1)

X_test_transformed

array([[0.        , 0.37410072, 0.56119403, ..., 0.        , 0.        ,
        0.        ],
       [0.5       , 0.96402878, 0.65820896, ..., 0.        , 0.        ,
        0.        ],
       [0.5       , 0.31654676, 0.48358209, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.5       , 0.27338129, 0.53628014, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.29496403, 0.54626866, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.4028777 , 0.5421981 , ..., 0.        , 0.        ,
        0.        ]])

In [244]:
pd.Series(predictions).value_counts()

1    138
0     62
dtype: int64

In [245]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[ 62,   0],
       [  0, 138]], dtype=int64)